import type { CaptionCue, CaptionStyle } from './manifest';

/**
 * Burned-in captions are rendered from an Advanced SubStation Alpha file via
 * libass rather than from chained `drawtext` filters. Three reasons, in
 * order of weight:
 *
 * 1. **Caption text never becomes a filter-graph argument.** FFmpeg's filter
 *    syntax gives `:`, `,`, `'`, `[` and `\` structural meaning, so putting
 *    operator- or agent-authored copy in a `drawtext=text=…` argument is an
 *    escaping problem with no safe general answer. A file has no such
 *    grammar, which is what docs/aamp-architecture.md §9's security note
 *    means by "caption text is passed via a file, not an argument".
 * 2. libass does real line wrapping, outlines and per-cue fades; `drawtext`
 *    does not wrap at all.
 * 3. One filter renders every cue, so cue count does not grow the graph.
 */

/** ASS colours are `&HAABBGGRR` — alpha first, then *reversed* RGB. */
export function toAssColor(hexRgb: string, alpha = 0): string {
  const hex = hexRgb.replace('#', '');
  const rr = hex.slice(0, 2);
  const gg = hex.slice(2, 4);
  const bb = hex.slice(4, 6);
  const aa = Math.max(0, Math.min(255, Math.round(alpha)))
    .toString(16)
    .padStart(2, '0');
  return `&H${aa}${bb}${gg}${rr}`.toUpperCase();
}

/** ASS timestamps are `H:MM:SS.cc` — centiseconds, single-digit hours. */
export function toAssTimestamp(seconds: number): string {
  const clamped = Math.max(0, seconds);
  const totalCentiseconds = Math.round(clamped * 100);
  const cs = totalCentiseconds % 100;
  const totalSeconds = (totalCentiseconds - cs) / 100;
  const ss = totalSeconds % 60;
  const totalMinutes = (totalSeconds - ss) / 60;
  const mm = totalMinutes % 60;
  const hh = (totalMinutes - mm) / 60;
  return `${hh}:${String(mm).padStart(2, '0')}:${String(ss).padStart(2, '0')}.${String(cs).padStart(2, '0')}`;
}

/**
 * Neutralises the only three sequences that carry meaning inside an ASS
 * dialogue line: brace-delimited override blocks, hard newlines, and the
 * backslash that introduces an escape. Everything else — including the
 * commas, colons and quotes that would be structural in a filter argument —
 * is ordinary text here.
 */
export function escapeAssText(text: string): string {
  return (
    text
      .replace(/\\/g, '∖')
      .replace(/\{/g, '(')
      .replace(/\}/g, ')')
      .replace(/\r\n?/g, '\n')
      .replace(/\n/g, '\\N')
      // Control characters have no rendering and can confuse the parser.
      // eslint-disable-next-line no-control-regex
      .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, '')
  );
}

export interface BuildAssInput {
  readonly style: CaptionStyle;
  readonly cues: readonly CaptionCue[];
  readonly widthPx: number;
  readonly heightPx: number;
  /** Per-cue fade, in milliseconds — the "animated typography" requirement applied to captions. */
  readonly fadeMs?: number;
}

const DEFAULT_CUE_FADE_MS = 120;

export function buildAssSubtitleFile(input: BuildAssInput): string {
  const { style } = input;
  const fadeMs = input.fadeMs ?? DEFAULT_CUE_FADE_MS;

  const header = [
    '[Script Info]',
    '; Generated by @combat/media — do not edit; regenerate from the render manifest.',
    'ScriptType: v4.00+',
    `PlayResX: ${input.widthPx}`,
    `PlayResY: ${input.heightPx}`,
    // 0 = smart wrapping with a wider lower line; captions read better than
    // the default when the last word would otherwise sit alone.
    'WrapStyle: 0',
    'ScaledBorderAndShadow: yes',
    'YCbCr Matrix: TV.709',
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    [
      'Style: Caption',
      sanitiseFontName(style.fontFamily),
      String(style.fontSizePx),
      toAssColor(style.primaryColorHex),
      toAssColor(style.primaryColorHex),
      toAssColor(style.outlineColorHex),
      // Semi-transparent backdrop shadow, so captions stay legible over a
      // bright frame without a solid box.
      toAssColor('#000000', 128),
      style.bold ? '-1' : '0',
      '0',
      '0',
      '0',
      '100',
      '100',
      '0',
      '0',
      '1', // BorderStyle 1 = outline + drop shadow
      String(style.outlineWidthPx),
      '2', // shadow depth
      '2', // Alignment 2 = bottom-centre
      String(style.marginHorizontalPx),
      String(style.marginHorizontalPx),
      String(style.marginBottomPx),
      '1',
    ].join(','),
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
  ];

  const events = input.cues.map((cue) => {
    const text = style.uppercase ? cue.text.toUpperCase() : cue.text;
    return [
      `Dialogue: 0`,
      toAssTimestamp(cue.startSeconds),
      toAssTimestamp(cue.endSeconds),
      'Caption',
      '',
      '0',
      '0',
      '0',
      '',
      `{\\fad(${fadeMs},${fadeMs})}${escapeAssText(text)}`,
    ].join(',');
  });

  // CRLF: libass accepts either, but ASS files are conventionally CRLF and
  // this keeps the generated file byte-identical across platforms.
  return [...header, ...events, ''].join('\r\n');
}

/** ASS style fields are comma-separated; a font name containing one would shift every later field. */
function sanitiseFontName(fontFamily: string): string {
  return fontFamily.replace(/[,\r\n]/g, ' ').trim() || 'Arial';
}
